// Generated by gencpp from file espeak_server/sayRequest.msg
// DO NOT EDIT!


#ifndef ESPEAK_SERVER_MESSAGE_SAYREQUEST_H
#define ESPEAK_SERVER_MESSAGE_SAYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace espeak_server
{
template <class ContainerAllocator>
struct sayRequest_
{
  typedef sayRequest_<ContainerAllocator> Type;

  sayRequest_()
    : sentence()  {
    }
  sayRequest_(const ContainerAllocator& _alloc)
    : sentence(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sentence_type;
  _sentence_type sentence;





  typedef boost::shared_ptr< ::espeak_server::sayRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::espeak_server::sayRequest_<ContainerAllocator> const> ConstPtr;

}; // struct sayRequest_

typedef ::espeak_server::sayRequest_<std::allocator<void> > sayRequest;

typedef boost::shared_ptr< ::espeak_server::sayRequest > sayRequestPtr;
typedef boost::shared_ptr< ::espeak_server::sayRequest const> sayRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::espeak_server::sayRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::espeak_server::sayRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace espeak_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::espeak_server::sayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::espeak_server::sayRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::espeak_server::sayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::espeak_server::sayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::espeak_server::sayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::espeak_server::sayRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::espeak_server::sayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ee8e7a1b3ec1e5b34263db750df6246";
  }

  static const char* value(const ::espeak_server::sayRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ee8e7a1b3ec1e5bULL;
  static const uint64_t static_value2 = 0x34263db750df6246ULL;
};

template<class ContainerAllocator>
struct DataType< ::espeak_server::sayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "espeak_server/sayRequest";
  }

  static const char* value(const ::espeak_server::sayRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::espeak_server::sayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sentence\n\
";
  }

  static const char* value(const ::espeak_server::sayRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::espeak_server::sayRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sentence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sayRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::espeak_server::sayRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::espeak_server::sayRequest_<ContainerAllocator>& v)
  {
    s << indent << "sentence: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sentence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ESPEAK_SERVER_MESSAGE_SAYREQUEST_H
