// Generated by gencpp from file robis_nav_msgs/get_pose_2D.msg
// DO NOT EDIT!


#ifndef ROBIS_NAV_MSGS_MESSAGE_GET_POSE_2D_H
#define ROBIS_NAV_MSGS_MESSAGE_GET_POSE_2D_H

#include <ros/service_traits.h>


#include <robis_nav_msgs/get_pose_2DRequest.h>
#include <robis_nav_msgs/get_pose_2DResponse.h>


namespace robis_nav_msgs
{

struct get_pose_2D
{

typedef get_pose_2DRequest Request;
typedef get_pose_2DResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_pose_2D
} // namespace robis_nav_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robis_nav_msgs::get_pose_2D > {
  static const char* value()
  {
    return "271cb12677c4cd9bccbc642cd9258d1f";
  }

  static const char* value(const ::robis_nav_msgs::get_pose_2D&) { return value(); }
};

template<>
struct DataType< ::robis_nav_msgs::get_pose_2D > {
  static const char* value()
  {
    return "robis_nav_msgs/get_pose_2D";
  }

  static const char* value(const ::robis_nav_msgs::get_pose_2D&) { return value(); }
};


// service_traits::MD5Sum< ::robis_nav_msgs::get_pose_2DRequest> should match 
// service_traits::MD5Sum< ::robis_nav_msgs::get_pose_2D > 
template<>
struct MD5Sum< ::robis_nav_msgs::get_pose_2DRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robis_nav_msgs::get_pose_2D >::value();
  }
  static const char* value(const ::robis_nav_msgs::get_pose_2DRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robis_nav_msgs::get_pose_2DRequest> should match 
// service_traits::DataType< ::robis_nav_msgs::get_pose_2D > 
template<>
struct DataType< ::robis_nav_msgs::get_pose_2DRequest>
{
  static const char* value()
  {
    return DataType< ::robis_nav_msgs::get_pose_2D >::value();
  }
  static const char* value(const ::robis_nav_msgs::get_pose_2DRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robis_nav_msgs::get_pose_2DResponse> should match 
// service_traits::MD5Sum< ::robis_nav_msgs::get_pose_2D > 
template<>
struct MD5Sum< ::robis_nav_msgs::get_pose_2DResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robis_nav_msgs::get_pose_2D >::value();
  }
  static const char* value(const ::robis_nav_msgs::get_pose_2DResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robis_nav_msgs::get_pose_2DResponse> should match 
// service_traits::DataType< ::robis_nav_msgs::get_pose_2D > 
template<>
struct DataType< ::robis_nav_msgs::get_pose_2DResponse>
{
  static const char* value()
  {
    return DataType< ::robis_nav_msgs::get_pose_2D >::value();
  }
  static const char* value(const ::robis_nav_msgs::get_pose_2DResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBIS_NAV_MSGS_MESSAGE_GET_POSE_2D_H
