// Generated by gencpp from file robis_nav_msgs/get_pose_2DRequest.msg
// DO NOT EDIT!


#ifndef ROBIS_NAV_MSGS_MESSAGE_GET_POSE_2DREQUEST_H
#define ROBIS_NAV_MSGS_MESSAGE_GET_POSE_2DREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robis_nav_msgs
{
template <class ContainerAllocator>
struct get_pose_2DRequest_
{
  typedef get_pose_2DRequest_<ContainerAllocator> Type;

  get_pose_2DRequest_()
    {
    }
  get_pose_2DRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::robis_nav_msgs::get_pose_2DRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robis_nav_msgs::get_pose_2DRequest_<ContainerAllocator> const> ConstPtr;

}; // struct get_pose_2DRequest_

typedef ::robis_nav_msgs::get_pose_2DRequest_<std::allocator<void> > get_pose_2DRequest;

typedef boost::shared_ptr< ::robis_nav_msgs::get_pose_2DRequest > get_pose_2DRequestPtr;
typedef boost::shared_ptr< ::robis_nav_msgs::get_pose_2DRequest const> get_pose_2DRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robis_nav_msgs::get_pose_2DRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robis_nav_msgs::get_pose_2DRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robis_nav_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robis_nav_msgs': ['/home/user/catkin_ws_ladybug/src/robis_custom_msgs_stack/robis_nav_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robis_nav_msgs::get_pose_2DRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robis_nav_msgs::get_pose_2DRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robis_nav_msgs::get_pose_2DRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robis_nav_msgs::get_pose_2DRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robis_nav_msgs::get_pose_2DRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robis_nav_msgs::get_pose_2DRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robis_nav_msgs::get_pose_2DRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::robis_nav_msgs::get_pose_2DRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::robis_nav_msgs::get_pose_2DRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robis_nav_msgs/get_pose_2DRequest";
  }

  static const char* value(const ::robis_nav_msgs::get_pose_2DRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robis_nav_msgs::get_pose_2DRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::robis_nav_msgs::get_pose_2DRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robis_nav_msgs::get_pose_2DRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_pose_2DRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robis_nav_msgs::get_pose_2DRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::robis_nav_msgs::get_pose_2DRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROBIS_NAV_MSGS_MESSAGE_GET_POSE_2DREQUEST_H
