// Generated by gencpp from file robis_nav_msgs/ParametricPathSet.msg
// DO NOT EDIT!


#ifndef ROBIS_NAV_MSGS_MESSAGE_PARAMETRICPATHSET_H
#define ROBIS_NAV_MSGS_MESSAGE_PARAMETRICPATHSET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robis_nav_msgs/ParametricPath.h>

namespace robis_nav_msgs
{
template <class ContainerAllocator>
struct ParametricPathSet_
{
  typedef ParametricPathSet_<ContainerAllocator> Type;

  ParametricPathSet_()
    : PathSet()
    , AuxNum0(0.0)  {
    }
  ParametricPathSet_(const ContainerAllocator& _alloc)
    : PathSet(_alloc)
    , AuxNum0(0.0)  {
  (void)_alloc;
    }



   typedef std::vector< ::robis_nav_msgs::ParametricPath_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::robis_nav_msgs::ParametricPath_<ContainerAllocator> >::other >  _PathSet_type;
  _PathSet_type PathSet;

   typedef float _AuxNum0_type;
  _AuxNum0_type AuxNum0;





  typedef boost::shared_ptr< ::robis_nav_msgs::ParametricPathSet_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robis_nav_msgs::ParametricPathSet_<ContainerAllocator> const> ConstPtr;

}; // struct ParametricPathSet_

typedef ::robis_nav_msgs::ParametricPathSet_<std::allocator<void> > ParametricPathSet;

typedef boost::shared_ptr< ::robis_nav_msgs::ParametricPathSet > ParametricPathSetPtr;
typedef boost::shared_ptr< ::robis_nav_msgs::ParametricPathSet const> ParametricPathSetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robis_nav_msgs::ParametricPathSet_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robis_nav_msgs::ParametricPathSet_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robis_nav_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robis_nav_msgs': ['/home/user/catkin_ws_ladybug/src/robis_custom_msgs_stack/robis_nav_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robis_nav_msgs::ParametricPathSet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robis_nav_msgs::ParametricPathSet_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robis_nav_msgs::ParametricPathSet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robis_nav_msgs::ParametricPathSet_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robis_nav_msgs::ParametricPathSet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robis_nav_msgs::ParametricPathSet_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robis_nav_msgs::ParametricPathSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ab4bf2b58281f53f77263e266fcaba1f";
  }

  static const char* value(const ::robis_nav_msgs::ParametricPathSet_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xab4bf2b58281f53fULL;
  static const uint64_t static_value2 = 0x77263e266fcaba1fULL;
};

template<class ContainerAllocator>
struct DataType< ::robis_nav_msgs::ParametricPathSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robis_nav_msgs/ParametricPathSet";
  }

  static const char* value(const ::robis_nav_msgs::ParametricPathSet_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robis_nav_msgs::ParametricPathSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robis_nav_msgs/ParametricPath[] PathSet\n\
float32 AuxNum0\n\
\n\
================================================================================\n\
MSG: robis_nav_msgs/ParametricPath\n\
float32 Velocity\n\
string FrameId\n\
string CurveType\n\
float32[] Fx\n\
float32[] Fy\n\
int64 Id\n\
";
  }

  static const char* value(const ::robis_nav_msgs::ParametricPathSet_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robis_nav_msgs::ParametricPathSet_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.PathSet);
      stream.next(m.AuxNum0);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ParametricPathSet_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robis_nav_msgs::ParametricPathSet_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robis_nav_msgs::ParametricPathSet_<ContainerAllocator>& v)
  {
    s << indent << "PathSet[]" << std::endl;
    for (size_t i = 0; i < v.PathSet.size(); ++i)
    {
      s << indent << "  PathSet[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::robis_nav_msgs::ParametricPath_<ContainerAllocator> >::stream(s, indent + "    ", v.PathSet[i]);
    }
    s << indent << "AuxNum0: ";
    Printer<float>::stream(s, indent + "  ", v.AuxNum0);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBIS_NAV_MSGS_MESSAGE_PARAMETRICPATHSET_H
