// Generated by gencpp from file robis_nav_msgs/PoseRobotEdge.msg
// DO NOT EDIT!


#ifndef ROBIS_NAV_MSGS_MESSAGE_POSEROBOTEDGE_H
#define ROBIS_NAV_MSGS_MESSAGE_POSEROBOTEDGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robis_nav_msgs
{
template <class ContainerAllocator>
struct PoseRobotEdge_
{
  typedef PoseRobotEdge_<ContainerAllocator> Type;

  PoseRobotEdge_()
    : Robot_id(0)
    , Edge_id(0)
    , Percentage_edge(0.0)  {
    }
  PoseRobotEdge_(const ContainerAllocator& _alloc)
    : Robot_id(0)
    , Edge_id(0)
    , Percentage_edge(0.0)  {
  (void)_alloc;
    }



   typedef int64_t _Robot_id_type;
  _Robot_id_type Robot_id;

   typedef int64_t _Edge_id_type;
  _Edge_id_type Edge_id;

   typedef float _Percentage_edge_type;
  _Percentage_edge_type Percentage_edge;





  typedef boost::shared_ptr< ::robis_nav_msgs::PoseRobotEdge_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robis_nav_msgs::PoseRobotEdge_<ContainerAllocator> const> ConstPtr;

}; // struct PoseRobotEdge_

typedef ::robis_nav_msgs::PoseRobotEdge_<std::allocator<void> > PoseRobotEdge;

typedef boost::shared_ptr< ::robis_nav_msgs::PoseRobotEdge > PoseRobotEdgePtr;
typedef boost::shared_ptr< ::robis_nav_msgs::PoseRobotEdge const> PoseRobotEdgeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robis_nav_msgs::PoseRobotEdge_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robis_nav_msgs::PoseRobotEdge_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robis_nav_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robis_nav_msgs': ['/home/user/catkin_ws_ladybug/src/robis_custom_msgs_stack/robis_nav_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robis_nav_msgs::PoseRobotEdge_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robis_nav_msgs::PoseRobotEdge_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robis_nav_msgs::PoseRobotEdge_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robis_nav_msgs::PoseRobotEdge_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robis_nav_msgs::PoseRobotEdge_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robis_nav_msgs::PoseRobotEdge_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robis_nav_msgs::PoseRobotEdge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7826d66e1f0b7b3f9fe4a380590b0ea5";
  }

  static const char* value(const ::robis_nav_msgs::PoseRobotEdge_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7826d66e1f0b7b3fULL;
  static const uint64_t static_value2 = 0x9fe4a380590b0ea5ULL;
};

template<class ContainerAllocator>
struct DataType< ::robis_nav_msgs::PoseRobotEdge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robis_nav_msgs/PoseRobotEdge";
  }

  static const char* value(const ::robis_nav_msgs::PoseRobotEdge_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robis_nav_msgs::PoseRobotEdge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 Robot_id\n\
int64 Edge_id\n\
float32 Percentage_edge\n\
";
  }

  static const char* value(const ::robis_nav_msgs::PoseRobotEdge_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robis_nav_msgs::PoseRobotEdge_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Robot_id);
      stream.next(m.Edge_id);
      stream.next(m.Percentage_edge);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseRobotEdge_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robis_nav_msgs::PoseRobotEdge_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robis_nav_msgs::PoseRobotEdge_<ContainerAllocator>& v)
  {
    s << indent << "Robot_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.Robot_id);
    s << indent << "Edge_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.Edge_id);
    s << indent << "Percentage_edge: ";
    Printer<float>::stream(s, indent + "  ", v.Percentage_edge);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBIS_NAV_MSGS_MESSAGE_POSEROBOTEDGE_H
