// Generated by gencpp from file robis_nav_msgs/RobotsPositionByEdge.msg
// DO NOT EDIT!


#ifndef ROBIS_NAV_MSGS_MESSAGE_ROBOTSPOSITIONBYEDGE_H
#define ROBIS_NAV_MSGS_MESSAGE_ROBOTSPOSITIONBYEDGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robis_nav_msgs/PoseRobotEdge.h>

namespace robis_nav_msgs
{
template <class ContainerAllocator>
struct RobotsPositionByEdge_
{
  typedef RobotsPositionByEdge_<ContainerAllocator> Type;

  RobotsPositionByEdge_()
    : RobotsPosition()  {
    }
  RobotsPositionByEdge_(const ContainerAllocator& _alloc)
    : RobotsPosition(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::robis_nav_msgs::PoseRobotEdge_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::robis_nav_msgs::PoseRobotEdge_<ContainerAllocator> >::other >  _RobotsPosition_type;
  _RobotsPosition_type RobotsPosition;





  typedef boost::shared_ptr< ::robis_nav_msgs::RobotsPositionByEdge_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robis_nav_msgs::RobotsPositionByEdge_<ContainerAllocator> const> ConstPtr;

}; // struct RobotsPositionByEdge_

typedef ::robis_nav_msgs::RobotsPositionByEdge_<std::allocator<void> > RobotsPositionByEdge;

typedef boost::shared_ptr< ::robis_nav_msgs::RobotsPositionByEdge > RobotsPositionByEdgePtr;
typedef boost::shared_ptr< ::robis_nav_msgs::RobotsPositionByEdge const> RobotsPositionByEdgeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robis_nav_msgs::RobotsPositionByEdge_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robis_nav_msgs::RobotsPositionByEdge_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robis_nav_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robis_nav_msgs': ['/home/user/catkin_ws_ladybug/src/robis_custom_msgs_stack/robis_nav_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robis_nav_msgs::RobotsPositionByEdge_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robis_nav_msgs::RobotsPositionByEdge_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robis_nav_msgs::RobotsPositionByEdge_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robis_nav_msgs::RobotsPositionByEdge_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robis_nav_msgs::RobotsPositionByEdge_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robis_nav_msgs::RobotsPositionByEdge_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robis_nav_msgs::RobotsPositionByEdge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3711249560d8afb64d700e4e5608fca1";
  }

  static const char* value(const ::robis_nav_msgs::RobotsPositionByEdge_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3711249560d8afb6ULL;
  static const uint64_t static_value2 = 0x4d700e4e5608fca1ULL;
};

template<class ContainerAllocator>
struct DataType< ::robis_nav_msgs::RobotsPositionByEdge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robis_nav_msgs/RobotsPositionByEdge";
  }

  static const char* value(const ::robis_nav_msgs::RobotsPositionByEdge_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robis_nav_msgs::RobotsPositionByEdge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PoseRobotEdge[] RobotsPosition\n\
\n\
================================================================================\n\
MSG: robis_nav_msgs/PoseRobotEdge\n\
int64 Robot_id\n\
int64 Edge_id\n\
float32 Percentage_edge\n\
";
  }

  static const char* value(const ::robis_nav_msgs::RobotsPositionByEdge_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robis_nav_msgs::RobotsPositionByEdge_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.RobotsPosition);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotsPositionByEdge_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robis_nav_msgs::RobotsPositionByEdge_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robis_nav_msgs::RobotsPositionByEdge_<ContainerAllocator>& v)
  {
    s << indent << "RobotsPosition[]" << std::endl;
    for (size_t i = 0; i < v.RobotsPosition.size(); ++i)
    {
      s << indent << "  RobotsPosition[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::robis_nav_msgs::PoseRobotEdge_<ContainerAllocator> >::stream(s, indent + "    ", v.RobotsPosition[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBIS_NAV_MSGS_MESSAGE_ROBOTSPOSITIONBYEDGE_H
