(cl:defpackage robis_nav_msgs-msg
  (:use )
  (:export
   "<PARAMETRICPATH>"
   "PARAMETRICPATH"
   "<PARAMETRICPATHSET>"
   "PARAMETRICPATHSET"
   "<PARAMETRICPATHSETWITHENDOFFSET>"
   "PARAMETRICPATHSETWITHENDOFFSET"
   "<POSE2DPAIR>"
   "POSE2DPAIR"
   "<POSE2DWITHCOVARIANCESTAMPED>"
   "POSE2DWITHCOVARIANCESTAMPED"
   "<POSEROBOTEDGE>"
   "POSEROBOTEDGE"
   "<ROBOTSPOSITIONBYEDGE>"
   "ROBOTSPOSITIONBYEDGE"
   "<TASKDECISION>"
   "TASKDECISION"
  ))

